# Generated by Django 4.0.6 on 2023-05-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0007_rename_rol_user_id_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_rol',
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(default='Digitador', max_length=50, verbose_name='Rol'),
        ),
    ]
