# Generated by Django 4.0.6 on 2023-06-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0008_remove_user_id_rol_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(max_length=50, verbose_name='Rol'),
        ),
    ]
